#!/bin/bash

if [ ! -d /data/git/.ssh ]; then
    mkdir -p /data/git/.ssh
    chmod 700 /data/git/.ssh
fi

if [ ! -f /data/git/.ssh/environment ]; then
    echo "GITBUNDLE_CUSTOM=$GITBUNDLE_CUSTOM" >| /data/git/.ssh/environment
    chmod 600 /data/git/.ssh/environment

elif ! grep -q "^GITBUNDLE_CUSTOM=$GITBUNDLE_CUSTOM$" /data/git/.ssh/environment; then
    sed -i /^GITBUNDLE_CUSTOM=/d /data/git/.ssh/environment
    echo "GITBUNDLE_CUSTOM=$GITBUNDLE_CUSTOM" >> /data/git/.ssh/environment
fi

if [ ! -f ${GITBUNDLE_CUSTOM}/conf/app.ini ]; then
    mkdir -p ${GITBUNDLE_CUSTOM}/conf

    # Set INSTALL_LOCK to true only if SECRET_KEY is not empty and
    # INSTALL_LOCK is empty
    if [ -n "$SECRET_KEY" ] && [ -z "$INSTALL_LOCK" ]; then
        INSTALL_LOCK=true
    fi

    # Substitute the environment variables in the template
    APP_NAME=${APP_NAME:-"GitBundle"} \
    RUN_MODE=${RUN_MODE:-"prod"} \
    DOMAIN=${DOMAIN:-"localhost"} \
    SSH_DOMAIN=${SSH_DOMAIN:-"localhost"} \
    HTTP_PORT=${HTTP_PORT:-"4000"} \
    ROOT_URL=${ROOT_URL:-""} \
    DISABLE_SSH=${DISABLE_SSH:-"false"} \
    SSH_PORT=${SSH_PORT:-"22"} \
    SSH_LISTEN_PORT=${SSH_LISTEN_PORT:-"${SSH_PORT}"} \
    LFS_START_SERVER=${LFS_START_SERVER:-"false"} \
    DB_TYPE=${DB_TYPE:-"mysql"} \
    DB_HOST=${DB_HOST:-"localhost:3306"} \
    DB_NAME=${DB_NAME:-"gitbundle"} \
    DB_USER=${DB_USER:-"root"} \
    DB_PASSWD=${DB_PASSWD:-""} \
    INSTALL_LOCK=${INSTALL_LOCK:-"false"} \
    DISABLE_REGISTRATION=${DISABLE_REGISTRATION:-"false"} \
    REQUIRE_SIGNIN_VIEW=${REQUIRE_SIGNIN_VIEW:-"false"} \
    SECRET_KEY=${SECRET_KEY:-""} \
    NSQD_CLUSTER_TCP_ADDR=${NSQD_CLUSTER_TCP_ADDR:-""} \
    REDIS_CONNECTION=${REDIS_CONNECTION:-""} \
    envsubst < /etc/templates/app.ini > ${GITBUNDLE_CUSTOM}/conf/app.ini

    chown ${USER}:git ${GITBUNDLE_CUSTOM}/conf/app.ini
fi

# Replace app.ini settings with env variables in the form GITBUNDLE__SECTION_NAME__KEY_NAME
environment-to-ini --config ${GITBUNDLE_CUSTOM}/conf/app.ini

# only chown if current owner is not already the gitbundle ${USER}. No recursive check to save time
if ! [[ $(ls -ld /data/gitbundle | awk '{print $3}') = ${USER} ]]; then chown -R ${USER}:git /data/gitbundle; fi
if ! [[ $(ls -ld /app/gitbundle | awk '{print $3}') = ${USER} ]]; then chown -R ${USER}:git /app/gitbundle;  fi
if ! [[ $(ls -ld /data/git   | awk '{print $3}') = ${USER} ]]; then chown -R ${USER}:git /data/git;   fi
chmod 0755 /data/gitbundle /app/gitbundle /data/git
