#!/bin/sh
#
# $OpenBSD$

daemon="/usr/local/bin/gitbundle"
daemon_user="git"
daemon_flags="web -c /etc/gitbundle/app.ini"

gitbundle_directory="/var/lib/gitbundle"

rc_bg=YES

. /etc/rc.d/rc.subr

rc_start() {
	${rcexec} "cd ${gitbundle_directory}; ${daemon} ${daemon_flags} ${_bg}"
}

rc_cmd $1
